service: thundra-demo-localstack

plugins:
  - serverless-deployment-bucket
  - serverless-localstack

package:
  artifact: ./target/thundra-demo-localstack.jar

custom:
  region: us-east-1
  accountID: '000000000000'
  localstack:
    stages: [local]
    debug: true
    autostart: true
    # lambda:
    #   mountCode: true

provider:
  name: aws
  stage: local
  region: us-east-1
  memorySize: 512
  timeout: 60
  deploymentBucket:
    name: thundra-demo-localstack-bucket
  environment:
    thundra_apikey: <YOUR-THUNDRA-API-KEY-HERE>

functions:
  helloService:
    handler: io.thundra.demo.localstack.handler.HelloHandler
    runtime: java8
    events:
      - http:
          path: /hello
          method: get
