service: thundra-demo-localstack

plugins:
  - serverless-deployment-bucket
  - serverless-localstack

package:
  artifact: ./target/thundra-demo-localstack.jar

custom:
  region: us-east-1
  accountID: '000000000000'
  localstack:
    stages: [local]
    debug: true
    autostart: true
    # lambda:
    #   mountCode: true

provider:
  name: aws
  stage: local
  region: us-east-1
  memorySize: 512
  timeout: 60
  deploymentBucket:
    name: thundra-demo-localstack-bucket

functions:
  http_handleRequest:
    handler: io.thundra.demo.localstack.handler.App
    runtime: java8
    events:
      - http:
          path: /requests
          method: post
      - http:
          path: /requests
          method: get
  backend_processRequest:
    handler: io.thundra.demo.localstack.handler.Processing
    runtime: java8
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ requestQueue, Arn ]
  backend_archiveResult:
    handler: io.thundra.demo.localstack.handler.Archive
    runtime: java8
    events:
      - sns: requestTopic

resources:
  Resources:
    appDatabase:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: appRequests
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: requestID
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: requestID
            KeyType: RANGE
    archiveBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: archivebucket
    requestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: requestQueue
